# Generated by Django 4.2.4 on 2023-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Remera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=128)),
                ("talle", models.IntegerField()),
                ("color", models.CharField(max_length=128)),
                ("lisa", models.BooleanField()),
                ("genero", models.IntegerField()),
            ],
        ),
    ]
