# Generated by Django 4.2.4 on 2023-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("cursos_asignados", models.IntegerField()),
            ],
        ),
    ]
