# Generated by Django 4.2.4 on 2023-09-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="turno",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Mañana"), (2, "Tarde"), (3, "Noche")], null=True
            ),
        ),
    ]
